### ISSUE TITLE
LookupError: unknown encoding: string-escape

### ISSUE THREAD

**Issue by jnkroeker** [mrlesmithjr/vagrant-vault-consul-docker-monitoring#2]
Thanks for all the great cloud formation learning resources you provide! I'm experiencing the below error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: LookupError: unknown encoding: string-escape
failed: [node0] (item=[u'build-essential', u'libffi-dev', u'libssl-dev', u'python-dev', u'python-pip', u'python-setuptools']) => {"changed": false, "cmd": "/usr/bin/apt-mark manual build-essential libffi-dev libssl-dev python-dev python-pip python-setuptools", "item": ["build-essential", "libffi-dev", "libssl-dev", "python-dev", "python-pip", "python-setuptools"], "msg": "unknown encoding: string-escape", "rc": 257}

My Googling has come up dry, other than the inkling I have it has do with my python version.

Ubuntu 16.04
Python  3.5.2
VBox     5.2
Vagrant 2.0.2
Ansible 2.7.5

**Comment by mrlesmithjr** [comment]
@jnkroeker Very welcome and hopefully you find some good usages. It does appear to be Python version related but not 100% sure. I'll do some testing as time permits and it appears that this repo needs some much needed love! Very outdated roles and etc.

**Comment by mrlesmithjr** [comment]
Have you tried creating a Python virtual environment with 2.7.x by chance to see if the same error occurs?

**Comment by mrlesmithjr** [comment]
@jnkroeker When you get a chance, delete the project and clone again using the following:
```bash
git clone https://github.com/mrlesmithjr/vagrant-vault-consul-docker-monitoring --recursive
```

Let's see if this resolves your issue and go from there.

Thanks!

**Comment by jnkroeker** [comment]
@mrlesmithjr Thanks for your reply. I have just solved this with your suggested python virtualenv with python 2.7 and ansible 2.3 installed. Looking forward to browsing the rest of your blog and repos to see what I can learn! Thanks again.

**Comment by mrlesmithjr** [comment]
@jnkroeker Awesome! Glad you got it sorted out.
